# Generated by Django 4.1.7 on 2023-04-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("GamePublisher", "0001_initial"),
        ("Game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                ("communityCode", models.AutoField(primary_key=True, serialize=False)),
                ("gameName", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Game.gamemodel"
                    ),
                ),
                (
                    "gamePublisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GamePublisher.gamepublisher",
                    ),
                ),
            ],
        ),
    ]
