# Generated by Django 4.1.7 on 2023-04-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0001_initial"),
        ("Community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="review",
            field=models.ForeignKey(
                default="no review yet",
                on_delete=django.db.models.deletion.CASCADE,
                to="Review.review",
            ),
        ),
    ]
