# Generated by Django 4.1.7 on 2023-04-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Community", "0002_community_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="gameName",
        ),
    ]
