# Generated by Django 4.1.7 on 2023-04-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GamePublisher",
            fields=[
                ("publisherCode", models.AutoField(primary_key=True, serialize=False)),
                ("pubPassword", models.CharField(max_length=255)),
                ("pubEmail", models.EmailField(max_length=254, unique=True)),
                (
                    "profilePicture",
                    models.ImageField(
                        blank=True, null=True, upload_to="publisher_pictures/"
                    ),
                ),
                ("publisherDescription", models.TextField()),
                ("publisherInfo", models.TextField()),
            ],
        ),
    ]
