# Generated by Django 4.1.7 on 2023-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GamePublisher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepublisher",
            name="profilePicture",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to="publisher_profile_pic_path",
            ),
        ),
    ]
