# Generated by Django 4.1.7 on 2023-04-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="collection",
        ),
    ]
