# Generated by Django 4.1.7 on 2023-03-13 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dateOfBirth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 13, 16, 15, 12, 89571, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
