# Generated by Django 4.1.7 on 2023-03-13 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0002_alter_user_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dateOfBirth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 13, 16, 19, 43, 766026, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
