# Generated by Django 4.1.7 on 2023-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0006_remove_user_issuperuser_alter_user_dateofbirth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dateOfBirth",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="userInfo",
            field=models.TextField(blank=True, default="", max_length=500, null=True),
        ),
    ]
