# Generated by Django 4.1.7 on 2023-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0007_alter_user_dateofbirth_alter_user_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
