# Generated by Django 4.1.7 on 2023-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0008_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profilePics/"
            ),
        ),
    ]
