# Generated by Django 4.1.7 on 2023-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0009_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to="C:\\Users\\rawal\\Software Development\\Roberts__Kennedy_and_Lawson\\GameCollectionPlatform\\media\\profilePics",
            ),
        ),
    ]
