# Generated by Django 4.1.7 on 2023-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0010_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to="C:\\Users\\15366\\OneDrive\\桌面\\Roberts__Kennedy_and_Lawson\\GameCollectionPlatform\\media\\profilePics",
            ),
        ),
    ]
