# Generated by Django 4.1.7 on 2023-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0012_alter_user_profilepic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="userCode",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
