# Generated by Django 4.1.7 on 2023-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Game", "0004_rename_pubname_gamemodel_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCollection",
            fields=[
                ("collectionCode", models.AutoField(primary_key=True, serialize=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Game.gamemodel"
                    ),
                ),
            ],
        ),
    ]
