# Generated by Django 4.1.7 on 2023-04-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCollection",
            fields=[
                ("collectionCode", models.AutoField(primary_key=True, serialize=False)),
                ("collectionName", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Game.gamemodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
