# Generated by Django 4.1.7 on 2023-04-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GamePublisher", "0002_alter_gamepublisher_profilepicture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecollection",
            name="collectionName",
            field=models.CharField(
                default="Default Collection", max_length=30, unique=True
            ),
        ),
        migrations.AddField(
            model_name="gamecollection",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GamePublisher.gamepublisher",
            ),
        ),
        migrations.AddField(
            model_name="gamecollection",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
