# Generated by Django 4.1.7 on 2023-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0004_rename_pubname_gamemodel_publisher"),
        ("Collection", "0002_gamecollection_collectionname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamecollection",
            name="game",
        ),
        migrations.AddField(
            model_name="gamecollection",
            name="game",
            field=models.ManyToManyField(to="Game.gamemodel"),
        ),
    ]
