# Generated by Django 4.1.7 on 2023-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("anonymous", "Anonymous"), ("public", "Public")],
                default="public",
                max_length=20,
            ),
        ),
    ]
