# Generated by Django 4.1.7 on 2023-04-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Review", "0002_alter_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewCode",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
