# Generated by Django 4.1.7 on 2023-04-04 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                ("gameCode", models.AutoField(primary_key=True, serialize=False)),
                ("gameName", models.CharField(max_length=255)),
                ("gameRate", models.FloatField()),
                ("gamePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gameDiscount", models.FloatField()),
                ("gameAge", models.IntegerField()),
                ("gameLabel", models.CharField(max_length=255)),
                (
                    "gamePublishDate",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("gameDescription", models.TextField()),
            ],
        ),
    ]
