# Generated by Django 4.1.7 on 2023-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="gameicon",
            field=models.ImageField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                upload_to="game_icon_path",
            ),
        ),
    ]
