# Generated by Django 4.1.7 on 2023-04-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GamePublisher", "0002_alter_gamepublisher_profilepicture"),
        ("Game", "0002_gamemodel_gameicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="pubName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GamePublisher.gamepublisher",
            ),
        ),
    ]
