# Generated by Django 4.1.7 on 2023-04-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Game", "0003_gamemodel_pubname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamemodel",
            old_name="pubName",
            new_name="publisher",
        ),
    ]
