# Generated by Django 4.1.7 on 2023-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collection", "0003_remove_gamecollection_game_gamecollection_game"),
        ("Game", "0004_rename_pubname_gamemodel_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="collection",
            field=models.ManyToManyField(to="Collection.gamecollection"),
        ),
    ]
